# Cluster Issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: amitgujar3342@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx

# ---
# apiVersion: cert-manager.io/v1alpha2
# kind: Certificate
# metadata:
#   name: production-certificate
# spec:
#   secretName: tls-secret-x
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt-prod
#   commonName: "*.akstest.tech"
#   dnsNames:
#     - "*.akstest.tech"
