neo4j:
  name: my-standalone-cdp
  resources:
    cpu: "2"
    memory: "5Gi"

  # password: "test1234"

# config:
#   server.memory.heap.initial_size: 3G
#   server.memory.heap.max_size: 3G
#   server.memory.pagecache.size: 1G

image:
  imagePullPolicy: IfNotPresent
  # set a customImage if you want to use your own docker image
  customImage: amitgujar/neofourj:beta

volumes:
  data:
    mode: "volume"
    volume:
      persistentVolumeClaim:
        claimName: neo4j-pvc-one

# helm upgrade --install my-neo4j neo4j/neo4j-standalone --values values.yml --version 4.3.2

# volumes:
#   data:
#     mode: "dynamic"
#     dynamic:
#       storageClassName: managed-csi

# services:
#   neo4j:
#     enabled: true
#     annotations: {}

#     spec:
#       type: LoadBalancer
#       # loadBalancerIP: 4.240.32.221

#     ports:
#       http:
#         enabled: true
#         port: 80
#         targetPort: 7474

#       https:
#         enabled: true 
#         port: 443
#         targetPort: 7473

#       bolt:
#         enabled: true
#         port: 7687
#         targetPort: 7687

startupProbe:
  failureThreshold: 1000
  periodSeconds: 40

ssl:
# setting per "connector" matching neo4j config
  bolt:
    privateKey:
      secretName: tls-secret
      subPath: tls.key
    publicCertificate:
      secretName: tls-secret
      subPath: tls.crt
  https:
    privateKey:
      secretName: tls-secret
      subPath: tls.key
    publicCertificate:
      secretName: tls-secret
      subPath: tls.crt
    trustedCerts:
      sources:
      - secret:
          name: tls-secret
          items:
          - key: tls.crt
            path: public.crt
  cluster:
    privateKey:
      secretName: tls-secret
      subPath: tls.key
    publicCertificate:
      secretName: tls-secret
      subPath: tls.crt
    trustedCerts:
      sources:
      - secret:
          name: tls-secret
          items:
          - key: tls.crt
            path: public.crt
    revokedCerts:
      sources: [ ]