neo4j:
  name: my-standalone
  resources:
    cpu: "0.5"
    memory: "4Gi"

  password: "test1234"

# volumes:
#   data:
#     mode: "volume"
#     volume:
#       storageClassName: standard-hdd

volumes:
  data:
    mode: "dynamic"
    dynamic:
      storageClassName: managed-csi